BanSachWeb/Controllers/SachController.cs
using BanSachWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using BanSachWeb.ViewModels;
using System.Data.Entity;
using Microsoft.Ajax.Utilities;
namespace BanSachWeb.Controllers
{
    public class SachController : Controller
    {
        // GET: Sach
        QuanLyBanSachModel db=new QuanLyBanSachModel();
        
        public ActionResult Index(int? page, decimal? minPrice, decimal? maxPrice)
        {
            int pageSize = 12;
            int pageNumber = (page ?? 1);

            var books = db.Saches.AsQueryable();

            if (minPrice.HasValue)
            {
                books = books.Where(b => b.GiaBan >= minPrice.Value);
            }

            if (maxPrice.HasValue)
            {
                books = books.Where(b => b.GiaBan <= maxPrice.Value);
            }

            var model = books.OrderBy(s => s.MaSach).Select(b => new BookViewModel
            {
                MaSach = b.MaSach,
                TenSach = b.TenSach,
                AnhSach = b.AnhSach,
                GiaBan = b.GiaBan,
                GiaGoc = b.GiaGoc,
                SoLuongDaBan = b.SoLuongDaBan,
                
            }).ToPagedList(pageNumber, pageSize);

            ViewBag.nameAction = "Index"; // Set the action name for pagination
            return View(model);
        }
        // GET: Book/GetCategories
        public ActionResult GetCategories()
        {
            var categories = db.DanhMucChinhs
                       .Include("DanhMucPhus")
                       .Where(c => c.DanhMucPhus.Any(s => s.Visible == true))
                       .ToList();

            // Alternatively, you might want to load only visible subcategories
            foreach (var category in categories)
            {
                category.DanhMucPhus = category.DanhMucPhus.Where(s => s.Visible == true).ToList();
            }

            
            return PartialView("GetCategories", categories);
        }
        public ActionResult ViewCategory(int id, int? page, decimal? minPrice, decimal? maxPrice)
        {
            var subCategory = db.DanhMucPhus.Find(id);
            if (subCategory == null)
            {
                return HttpNotFound();
            }

            ViewBag.Title = "Sách theo danh mục - " + subCategory.TenDanhMuc;
            ViewBag.nameAction = "ViewCategory";
            ViewBag.minPrice = minPrice;
            ViewBag.maxPrice = maxPrice;

            var products = db.Saches.Where(s => s.MaDanhMuc == id);

            if (minPrice.HasValue)
            {
                products = products.Where(s => s.GiaBan >= minPrice.Value);
            }

            if (maxPrice.HasValue)
            {
                products = products.Where(s => s.GiaBan <= maxPrice.Value);
            }

            int pageSize = 12;
            int pageNumber = (page ?? 1);
            var productViewModels = products.OrderBy(s => s.MaSach).Where(s => s.Visible == true).Select(s => new BookViewModel
            {
                MaSach = s.MaSach,
                TenSach = s.TenSach,
                SoLuongDaBan = s.SoLuongDaBan,
                AnhSach = s.AnhSach,
                GiaBan = s.GiaBan,
                GiaGoc = s.GiaGoc
            }).ToPagedList(pageNumber, pageSize);

            return View("Index", productViewModels);
        }



        public IQueryable<BookViewModel> GetBookQuery()
        {
            return db.Saches.AsNoTracking()
                .Select(s => new BookViewModel
                {
                    MaSach = s.MaSach,
                    TenSach = s.TenSach,
                    SoLuongDaBan = s.SoLuongDaBan,
                    AnhSach = s.AnhSach,
                    GiaBan = s.GiaBan,
                    GiaGoc = s.GiaGoc
                });
        }
        public IQueryable<BookViewModel> GetTopBookQuery(int amount = 24)
        {

            return db.Saches.Where(s => s.Visible == true)
                .Select(s => new BookViewModel
                {
                    MaSach = s.MaSach,
                    TenSach = s.TenSach,
                    SoLuongDaBan = s.SoLuongDaBan,
                    AnhSach = s.AnhSach,
                    GiaBan = s.GiaBan,
                    GiaGoc = s.GiaGoc
                }).OrderByDescending(s => s.SoLuongDaBan).Take(amount);
        }
        


        public ActionResult SachDetail(int id)
        {
            var book = db.Saches.FirstOrDefault(s => s.MaSach == id);
            if (book == null)
            {
                return HttpNotFound();
            }

            var relevantBooks = db.Saches
                .Where(s => s.MaDanhMuc == book.MaDanhMuc && s.MaSach != id&&s.Visible==true)
                .Take(4) // limit to 5 relevant books
                .ToList();

            var model = new BookDetailsViewModel
            {
                Book = book,
                RelevantBooks = relevantBooks
            };

            return View(model);
        }
        public ActionResult TopSale(int? page, decimal? minPrice, decimal? maxPrice)
        {
            int pageNumber = (page ?? 1);
            int pageSize = 12;
            var topBooks = GetTopBookQuery().AsQueryable();
            if (minPrice.HasValue)
            {
                topBooks = topBooks.Where(s => s.GiaBan >= minPrice.Value);
            }

            if (maxPrice.HasValue)
            {
                topBooks = topBooks.Where(s => s.GiaBan <= maxPrice.Value);
            }
            ViewBag.Title = "Sách bán chạy";
            ViewBag.nameAction = "TopSale";
            ViewBag.minPrice = minPrice;
            ViewBag.maxPrice = maxPrice;
           var topBookspagelist=topBooks.ToPagedList(pageNumber, pageSize);
            return View("Index", topBookspagelist);
        }
        public PartialViewResult TopSalePartial()
        {
            var topSaleBooks = GetTopBookQuery(4);
            return PartialView("_TopSale", topSaleBooks);
        }

        public IQueryable<BookViewModel> GetSearchedBookQuery(List<Sach> sachs)
        {
            return sachs.Select(s => new BookViewModel
            {
                MaSach = s.MaSach,
                TenSach = s.TenSach,
                SoLuongDaBan = s.SoLuongDaBan,
                AnhSach = s.AnhSach,
                GiaBan = s.GiaBan,
                GiaGoc = s.GiaGoc
            }).AsQueryable();
        }
        //Xử lý phần tìm kiếm
        // API to get search suggestions
        public JsonResult GetSuggestions(string term)
        {
            if (string.IsNullOrEmpty(term))
            {
                return Json(new List<string>(), JsonRequestBehavior.AllowGet);
            }

            term = RemoveVietnameseDiacritics(term.ToLower());
            var saches = db.Saches.ToList();
            var suggestions = saches
                .Where(s => RemoveVietnameseDiacritics(s.TenSach.ToLower()).Contains(term))
                .Select(s => s.TenSach)
                .Distinct()
                .Take(10)
                .ToList();

            return Json(suggestions, JsonRequestBehavior.AllowGet);
        }
        private string RemoveVietnameseDiacritics(string text)
        {
            string[] VietnameseChars = new string[]
            {
            "aAeEoOuUiIdDyY",
            "áàạảãâấầậẩẫăắằặẳẵ",
            "ÁÀẠẢÃÂẤẦẬẨẪĂẮẰẶẲẴ",
            "éèẹẻẽêếềệểễ",
            "ÉÈẸẺẼÊẾỀỆỂỄ",
            "óòọỏõôốồộổỗơớờợởỡ",
            "ÓÒỌỎÕÔỐỒỘỔỖƠỚỜỢỞỠ",
            "úùụủũưứừựửữ",
            "ÚÙỤỦŨƯỨỪỰỬỮ",
            "íìịỉĩ",
            "ÍÌỊỈĨ",
            "đ",
            "Đ",
            "ýỳỵỷỹ",
            "ÝỲỴỶỸ"
            };

            for (int i = 1; i < VietnameseChars.Length; i++)
            {
                for (int j = 0; j < VietnameseChars[i].Length; j++)
                    text = text.Replace(VietnameseChars[i][j], VietnameseChars[0][i - 1]);
            }
            return text;
        }

        public ActionResult Search(SearchViewModel model, int? page, decimal? minPrice, decimal? maxPrice)
        {
            
            if (model == null)
            {
                System.Diagnostics.Debug.WriteLine("Model is null.");
                return RedirectToAction("Index");

            }
            var searchKey = RemoveVietnameseDiacritics(model.SearchKey?.ToLower() ?? "");
            if (searchKey.IsNullOrWhiteSpace())
            {
                System.Diagnostics.Debug.WriteLine("searchkey is empty.");
            }// Null conditional operator and null coalescing operator are used here
            var saches = db.Saches.ToList();
            var tacGias = db.TacGias.ToList();

            var sachViewModelList = (from s in saches
                                     join t in tacGias on s.MaTacGia equals t.MaTacGia into authorGroup
                                     from t in authorGroup.DefaultIfEmpty()
                                     let tenTacGia = t != null ? t.TenTacGia : ""
                                     let tenSach = s.TenSach
                                     where RemoveVietnameseDiacritics((tenTacGia ?? "").ToLower()).Contains(searchKey) ||
                                           RemoveVietnameseDiacritics((tenSach ?? "").ToLower()).Contains(searchKey)
                                     select new BookViewModel
                                     {
                                         MaSach = s.MaSach,
                                         TenSach = s.TenSach,
                                         SoLuongDaBan = s.SoLuongDaBan,
                                         AnhSach = s.AnhSach,
                                         GiaBan = s.GiaBan,
                                         GiaGoc = s.GiaGoc,
                                         TenTacGia = t != null ? t.TenTacGia : "Unknown"
                                     }).AsQueryable();

BanSachWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home page</title>
    <link rel="stylesheet" href="~/Content/HomeStyle.css">
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
          integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A=="
          crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <div class="m_top sticky-top">
        <section class="header ">
            <div class="container py-3">
                <div class="row">
                    <div class="col-md-2">
                        <span class="fs-3">
                            <a href="/Home"><img src="~/Image/sachhayvn-high-resolution-logo-black-transparent.png" alt="logo" class="img-fluid" /></a>
                        </span>
                    </div>

                    <div class="col-md-6 ">
                        <div class="input-group mb-3">
                            @using (Html.BeginForm("Search", "Sach", FormMethod.Post, new { id = "searchForm" }))
                            {
                                <input class="mr-sm-2" type="text" id="searchBox" name="SearchKey" placeholder="Nhập từ khóa" list="suggestions" autocomplete="off" value="@ViewBag.SearchKey" />
                                <datalist id="suggestions"></datalist>

                                <button type="submit" class="btn btn-primary" onclick="return validateSearchKey()">Search</button>

                            }
                        </div>
                    </div>


                    @if (Session["emailOrPhone"] == null)
                    {
                        <div class="col-md-2 ">
                            <a href="/Register" id="Register" class="btn btn-outline-success">Đăng ký</a>
                            <a href="/Login" id="Login" class="btn btn-outline-danger">Đăng nhập</a>
                        </div>
                    }
                    else
                    {

                        <div class="col-md-2 ">
                            <a href="/Cart/Index" class="text-decoration-none position-relative" style="color:black">
                                <div class="">
                                    <span class="fs-3"><i class="fa-solid fa-cart-shopping"></i></span>
                                    <span class="fs-5">Giỏ hàng</span>

                                </div>
                            </a>
                        </div>
                    }
                </div>
            </div>
        </section>

        <section class="main_nav">
            <div class="container" id="menu">
                <div class="col-6 ps-5">
                    <div class="dropdown" id="myDropdown">
                        <p id="dr" class="dropdown-toggle m-0 py-2">
                            <i class="fa-solid fa-list"></i>
                            Danh mục sách
                        </p>
                        <ul id="sdm" class="dropdown-menu mt-2">
                            @Html.Action("GetCategories", "Sach")
                        </ul>
                    </div>
                </div>
                <div class="col-9">
                    <ul id="mn">
                        <li><a href="/Home">Trang chủ</a></li>
                        <li><a href="/Sach/TopSale">Sách bán chạy</a></li>
                        <li><a href="#">Khuyến mãi</a></li>
                        @if (Session["username"] != null)
                        {
                            <li>
                                <a href="#">@Session["username"]</a>
                                <ul id="sub">

                                    <li>@Html.ActionLink("Cập nhật thông tin", "UpdateAccountInfo", "Account")</li>
                                    <li>@Html.ActionLink("Đăng xuất", "Logout", "Account")</li>
                                    <li>@Html.ActionLink("Danh sách đơn hàng", "UserOrders", "Cart")</li>
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </section>
    </div>


    <section class="content">
        @RenderBody()

    </section>

    <section class="main_footer">
        <div class="container">
            <div class="row">
                <div class="col-4">
                    <ul class="sub_foot">
                        <li><h2>SachHay.vn</h2></li>
                        <li><h3>Địa chỉ:</h3></li>
                        <li><p>Trường đại học công nghiệp Hà Nội</p></li>
                        <li><h3>Liên hệ</h3></li>
                        <li><p>Email:manbahao1508@gmail.com</p></li>
                        <li><p>SDT: 012345678</p></li>
                    </ul>
                </div>
                <div class="col-4">
                    <ul class="sub_foot">
                        <li> <h3>Dịch vụ</h3></li>
                        <li><a href="#">Điều khoản sử dụng</a></li>
                        <li><a href="#">Chính sách bảo mật</a></li>
                        <li><a href="#">Chính sách thanh toán</a></li>
                        <li><a href="#">Về SachHay.vn</a></li>
                    </ul>
                </div>
                <div class="col-4">
                    <ul class="sub_foot">
                        <li><h3>Hỗ trợ</h3></li>
                        <li><a href="#">Chính sách đổi - trả - hoàn tiền</a></li>
                        <li><a href="#">Chính sách vận chuyển</a></li>
                        <li><a href="#">Phương thức thanh toán</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <p style="text-align:center">Copyright by HaUI.</p>
    </section>





    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.7.1.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/Scripts/jquery-3.7.1.min.js"></script>

    <script>
            $(document).ready(function () {
                $('.dropdown-toggle').click(function () {
                    $(this).next('.dropdown-menu').toggle();
                });
            });
            $('#searchBox').keyup(function () {
                var query = $(this).val();
                if (query.length > 2) {
                    $.ajax({
                        url: '@Url.Action("GetSuggestions", "Sach")',
                        data: { term: query },
                        success: function (data) {
                            $('#suggestions').empty();
                            $.each(data, function (index, value) {
                                $('#suggestions').append('<option value="' + value + '">');
                            });
                        }
                    });
                }
            });

            $(document).on('click', '#suggestionsList li', function () {
                $('#searchBox').val($(this).text());
                $('#suggestionsList').hide();
            });

    </script>
    <script>
        function validateSearchKey() {
            var searchKey = document.getElementById("searchBox").value;
            if (searchKey.trim() === "") {
                alert("Please enter a search key.");
                return false;
            }
            return true;
        }
    </script>


    @RenderSection("scripts", required: false)




</body>

</html>

BanSachWeb/Views/Shared/_TopSale.cshtml
@using PagedList.Mvc;
@model IEnumerable<BanSachWeb.Models.BookViewModel>


<div class="container">
    <h2 class="mt-5">Sách bán chạy</h2>
    <p class="d-flex justify-content-end">@Html.ActionLink("Xem tất cả", "TopSale", "Sach")</p>
    <div class="row justify-content-center">
        @foreach (var product in Model)
        {
            <div class="col-sm-6 col-md-4 col-lg-3 mb-5 ">
                <div class="card h-100 custom-card">
                    <a href="@Url.Action("SachDetail", "Sach", new { id = product.MaSach })" style="text-decoration:none;color:black">
                        <div class="card h-100 custom-card">
                            <!-- Sale badge-->
                            <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">Giảm: @product.DiscountPercentage%</div>
                            <!-- Product image-->
                            <img class="card-img-top product-image" src="@Url.Content("~/Content/Image/" + product.AnhSach)" alt="Product Image" />
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">@product.TenSach</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        <div class="bi-star-fill">⭐</div>
                                    </div>
                                    <!-- Product price-->
                                    <span class="text-muted text-decoration-line-through">@product.GiaGoc</span>
                                    @product.GiaBan
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center">Da ban: @product.SoLuongDaBan</div>
                            </div>
                        </div>
                    </a>
                    <div class="row">
                        <div class="col-2 "></div>
                        <div class="col-4 ">
                            @using (Html.BeginForm("BuyNow", "Cart", FormMethod.Post))
                            {
                                @Html.Hidden("maSach", product.MaSach)
                                @Html.Hidden("quantity", 1)
                                <button type="submit" class="btn btn-success">Mua</button>
                            }
                        </div>
                        <div class="col-4">
                            @using (Html.BeginForm("AddToCart", "Cart", FormMethod.Post, new { @class = "add-to-cart-form" }))
                            {
                                @Html.Hidden("maSach", product.MaSach) <!-- Sử dụng Hidden field để truyền mã sách quantity -->
                                @Html.Hidden("quantity", 1)
                                <button type="submit" class="btn btn-primary add-to-cart-button_sale">Thêm</button> <!-- Added the class here -->
                            }
                        </div>
                    </div>

                </div>

            </div>
        }
    </div>
   
    <style>
        .product-image {
            width: 100%;
            height: 200px; /* Set a fixed height */
            object-fit: cover; /* Maintain aspect ratio and cover the entire area */
        }
        .card{

        }
    </style>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        $('.add-to-cart-button_sale').off('click').click(function (event) {
            event.preventDefault(); // Prevent default form submission
            var form = $(this).closest('form');
            var formData = form.serialize();
            
            $.ajax({
                type: 'POST',
                url: form.attr('action'),
                data: formData,
                success: function (response) {
                    if (response.success) {
                       
                        alert('Thêm vào giỏ hàng thành công!');
                       
                        
                    } else {
                        if (response.notLoggedIn) {
                           
                            alert('Vui lòng đăng nhập.');
                            
                            // Optionally, redirect to the login page
                            window.location.href = '/Account/Login';
                            
                        } else {
                            alert('Thêm vào giỏ hàng thất bại.');
                        }
                    }
                },
                error: function () {
                    alert('Có lỗi xảy ra. Vui lòng thử lại.');
                }
            });
        });
    });
</script>

</div>