BanSachWeb/Models/DiaChi.cs
namespace BanSachWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("DiaChi")]
    public partial class DiaChi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiaChi()
        {
            DonHangs = new HashSet<DonHang>();
        }

        [Key]
        public int MaDiaChi { get; set; }

        public string DiaChiCuThe { get; set; }

        public bool? MacDinh { get; set; }

        [StringLength(15)]
        public string SoDienThoaiNhanHang { get; set; }

        [StringLength(255)]
        public string TenNguoiNhan { get; set; }

        public int? MaTaiKhoan { get; set; }

        public virtual TaiKhoan TaiKhoan { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}

BanSachWeb/Controllers/DiaChisController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BanSachWeb.Models;

namespace BanSachWeb.Controllers
{
    public class DiaChisController : Controller
    {
        private QuanLyBanSachModel db = new QuanLyBanSachModel();

        // GET: DiaChis
        public ActionResult Index()
        {
            var userId = (int)Session["MaTaiKhoan"];
            var diaChis = db.DiaChis.Where(d => d.MaTaiKhoan == userId).ToList();
            return View(diaChis);
        }

        

        // GET: DiaChis/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DiaChis/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDiaChi,DiaChiCuThe,MacDinh,SoDienThoaiNhanHang,TenNguoiNhan")] DiaChi diaChi)
        {
            if (ModelState.IsValid)
            {
                // Retrieve the user's account information from the session
                var userEmailOrPhone = Session["emailOrPhone"] as string;
                var user = db.TaiKhoans.FirstOrDefault(u => u.Email == userEmailOrPhone || u.SoDienThoai == userEmailOrPhone);

                if (user != null)
                {
                    // Set the MaTaiKhoan property of the new address
                    diaChi.MaTaiKhoan = user.MaTaiKhoan;
                    // If this address is set as default, reset the MacDinh field for other addresses
                    if (diaChi.MacDinh.Value==true)
                    {
                        var existingAddresses = db.DiaChis.Where(d => d.MaTaiKhoan == user.MaTaiKhoan);
                        foreach (var address in existingAddresses)
                        {
                            address.MacDinh = false;
                        }
                    }

                    db.DiaChis.Add(diaChi);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "User not found. Please log in again.");
                }
            }

            return View(diaChi);
        }
        // GET: DiaChis/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DiaChi diaChi = db.DiaChis.Find(id);
            if (diaChi == null || diaChi.MaTaiKhoan != (int)Session["MaTaiKhoan"]) // Ensure it belongs to the logged-in user
            {
                return HttpNotFound();
            }
            return View(diaChi);
        }

        // POST: DiaChis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Edit([Bind(Include = "MaDiaChi,DiaChiCuThe,MacDinh,SoDienThoaiNhanHang,TenNguoiNhan")] DiaChi diaChi)
        {
            if (ModelState.IsValid)
            {
                diaChi.MaTaiKhoan = (int)Session["MaTaiKhoan"];

                // Check if the address exists in the database
                var existingDiaChi = db.DiaChis.SingleOrDefault(d => d.MaDiaChi == diaChi.MaDiaChi && d.MaTaiKhoan == diaChi.MaTaiKhoan);
                if (existingDiaChi == null)
                {
                    return HttpNotFound();
                }

                // If this address is set as default, reset the MacDinh field for other addresses
                if (diaChi.MacDinh.Value == true)
                {
                    var existingAddresses = db.DiaChis.Where(d => d.MaTaiKhoan == diaChi.MaTaiKhoan && d.MaDiaChi != diaChi.MaDiaChi).ToList();
                    foreach (var address in existingAddresses)
                    {
                        address.MacDinh = false;
                        db.Entry(address).State = EntityState.Modified;
                    }
                }

                // Update the current address
                existingDiaChi.DiaChiCuThe = diaChi.DiaChiCuThe;
                existingDiaChi.MacDinh = diaChi.MacDinh;
                existingDiaChi.SoDienThoaiNhanHang = diaChi.SoDienThoaiNhanHang;
                existingDiaChi.TenNguoiNhan = diaChi.TenNguoiNhan;

                db.Entry(existingDiaChi).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(diaChi);
        }


        // GET: DiaChis/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DiaChi diaChi = db.DiaChis.Find(id);
            if (diaChi == null)
            {
                return HttpNotFound();
            }
            return View(diaChi);
        }

        // POST: DiaChis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DiaChi diaChi = db.DiaChis.Find(id);
            db.DiaChis.Remove(diaChi);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BanSachWeb/Views/DiaChis/Create.cshtml
@model BanSachWeb.Models.DiaChi

@{
    ViewBag.Title = "Tạo mới địa chỉ nhận hàng";
}

<style>

    .form-horizontal {
        border: 1px solid #ccc; /* Màu và độ dày của viền */
        border-radius: 5px; /* Đường cong viền */
        padding: 20px; /* Khoảng cách bên trong form */
        width: 70%;
    }


    /* Căn chỉnh khoảng cách giữa các nút */
    .btn-group {
        margin-top: 20px; /* Khoảng cách từ các nút đến các thành phần trên */
    }

    /* Thêm một ít không gian giữa các nút và các thành phần trên */
    .form-group {
        margin-bottom: 15px;
    }

    #td {
        text-align: center;
        margin: 10px;
        padding: 5px;
    }

    .control-label {
        font-weight: bold;
        padding: 5px;
    }
</style>

<h2 id="td">Thêm địa chỉ nhận hàng mới</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row justify-content-center">
            <div class="form-horizontal mx-4 mb-4">


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.DiaChiCuThe, "Địa chỉ cụ thể", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        @Html.EditorFor(model => model.DiaChiCuThe, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DiaChiCuThe, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MacDinh, "Mặc định", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        <div class="checkbox">
                            @Html.EditorFor(model => model.MacDinh)
                            @Html.ValidationMessageFor(model => model.MacDinh, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SoDienThoaiNhanHang, "Số điện thoại nhận hàng", htmlAttributes: new { @class = "control-label col-md-4" })
                    <div>
                        @Html.EditorFor(model => model.SoDienThoaiNhanHang, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SoDienThoaiNhanHang, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TenNguoiNhan, "Tên người nhận", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        @Html.EditorFor(model => model.TenNguoiNhan, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenNguoiNhan, "", new { @class = "text-danger" })
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Tạo mới" class="btn btn-primary" />
                        <a href="@Url.Action( "Index", "DiaChis")" class="btn btn-danger btn-user btn-block mx-3">Hủy bỏ</a>
                    </div>
                </div>

                <div style="text-align:right">
                    @Html.ActionLink("Quản lý thông tin nhận hàng", "Index")
                </div>
            </div>
        </div>
    </div>
}

BanSachWeb/Views/DiaChis/Delete.cshtml
@model BanSachWeb.Models.DiaChi

@{
    ViewBag.Title = "Delete";
}



<h2>Xóa địa chỉ</h2>

<h3>Bạn có chắc chắn muốn xóa địa chỉ này?</h3>
<div>
    <h4>Địa chỉ</h4>
    <hr />
    <dl class="dl-horizontal" style="border: 1px solid #ddd; padding: 10px; border-radius: 5px; margin:20px;">
        <dt style="margin-bottom: 10px;">Thông tin đầy đủ</dt>
        <dd style="margin-bottom: 10px;">
            <strong>Địa chỉ cụ thể:</strong> @Html.DisplayFor(model => model.DiaChiCuThe) <br />
            <strong>Số điện thoại nhận hàng:</strong> @Html.DisplayFor(model => model.SoDienThoaiNhanHang) <br />
            <strong>Tên người nhận:</strong> @Html.DisplayFor(model => model.TenNguoiNhan)
        </dd>
        <dt style="margin-bottom: 10px;">@Html.DisplayNameFor(model => model.MacDinh)</dt>
        <dd style="margin-bottom: 10px;">@Html.DisplayFor(model => model.MacDinh)</dd>
    </dl>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-actions no-color" style="margin: 20px;">
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a href="@Url.Action( "Index", "DiaChis")" class="btn btn-secondary" style="margin-left: 10px;">Cancel</a>
    </div>
}
</div>

BanSachWeb/Views/DiaChis/Edit.cshtml
@model BanSachWeb.Models.DiaChi

@{
    ViewBag.Title = "Edit";
}

<style>
    /* CSS */
    .form-horizontal {
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        margin: 20px;
        width: 60%;
    }

    .form-group {
        margin-bottom: 15px;
        width: 100%;
    }

    .control-label {
        font-weight: bold;
        padding: 5px;
    }

    .btn {
        margin-right: 10px;
    }

    #td {
        text-align: center;
        padding-top: 10px;
    }
</style>

<h2 id="td">Cập nhật thông tin địa chỉ</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="row justify-content-center">
            <div class="form-horizontal mx-5">

                @Html.ValidationSummary(true, "", new { @class = "text-danger", disable = "disabled" })
                @Html.HiddenFor(model => model.MaDiaChi)

                <div class="form-group">
                    @Html.LabelFor(model => model.DiaChiCuThe, "Địa chỉ cụ thể", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        @Html.EditorFor(model => model.DiaChiCuThe, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DiaChiCuThe, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.MacDinh, "Mặc định", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        <div class="checkbox">
                            @Html.EditorFor(model => model.MacDinh)
                            @Html.ValidationMessageFor(model => model.MacDinh, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SoDienThoaiNhanHang, "Số điện thoại nhận hàng", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        @Html.EditorFor(model => model.SoDienThoaiNhanHang, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SoDienThoaiNhanHang, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TenNguoiNhan, "Tên người nhận", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div>
                        @Html.EditorFor(model => model.TenNguoiNhan, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TenNguoiNhan, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Lưu" class="btn btn-primary" />
                        <a href="@Url.Action("Index", "DiaChis")" class="btn btn-danger btn-user btn-block">Hủy bỏ</a>
                    </div>
                </div>

                <div style="text-decoration:none; margin:10px; text-align:right">
                    @Html.ActionLink("Quản lý thông tin nhận hàng", "Index", "DiaChis")
                </div>
            </div>

        </div>
    </div>

}

BanSachWeb/Views/DiaChis/Index.cshtml
@model IEnumerable<BanSachWeb.Models.DiaChi>

@{
    ViewBag.Title = "Quản lý thông tin nhận hàng";
}


<style>
    #tieude {
        text-align: center;
        margin: 10px;
    }

    .but {
        margin: 20px;
    }

    .table {
        margin-left: 20px;
    }
</style>

<h2 id="tieude">Quản lý thông tin nhận hàng</h2>

<div class="but">
    <button type="button" class="btn btn-primary">
        @Html.ActionLink("Thêm mới", "Create", null, new { @class = "text-white", style = "text-decoration: none;" })
    </button>
</div>

<table class="table">
    <tr>

        <th>
            Thông tin đầy đủ
        </th>
        <th>
            Mặc định
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <strong>Địa chỉ cụ thể:</strong> @Html.DisplayFor(modelItem => item.DiaChiCuThe) <br />
                <strong>Số điện thoại nhận hàng:</strong> @Html.DisplayFor(modelItem => item.SoDienThoaiNhanHang) <br />
                <strong>Tên người nhận:</strong> @Html.DisplayFor(modelItem => item.TenNguoiNhan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MacDinh)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.MaDiaChi }, new { @class = "text-black", style = "text-decoration: none;" }) |

                @Html.ActionLink("Xóa", "Delete", new { id = item.MaDiaChi }, new { @class = "text-black", style = "text-decoration: none;" })
            </td>
            @if (item.MacDinh.HasValue && item.MacDinh.Value)
            {


                Session["madiachi"] = item.MaDiaChi;
            }

        </tr>
    }

</table>
<div class="but">
    <button type="button" class="btn btn-primary">
        @Html.ActionLink("Back", "UpdateAccountInfo", "Account", null, new { @class = "text-white", style = "text-decoration: none;" })
    </button>
</div>
<div>
    <a href="@Url.Action("OrderConfirmation", "Cart", new { orderId = Session["oderID"] })">Back to Order Confirmation</a>
</div>